version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps"
    assignees:
      - "devparada"

    open-pull-requests-limit: 4

    # Agrupa las actualizaciones en un único PR
    groups:
      deps:
        patterns:
          - "*"
